apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notifications-microservice
  template:
    metadata:
      labels:
        app: notifications-microservice
    spec:
      containers:
      - name: notifications-microservice
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8083
