apiVersion: v1
kind: Service
metadata:
  name: notifications-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: notifications-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8083
