apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: transfer-microservice
  template:
    metadata:
      labels:
        app: transfer-microservice
    spec:
      containers:
      - name: transfer-microservice
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8086
