apiVersion: v1
kind: Service
metadata:
  name: transfer-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: transfer-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8086
