replicaCount: 1

image:
  repository: accounts-microservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081
  nodePort: 30081

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
  SPRING_DATASOURCE_USERNAME: myuser
  SPRING_DATASOURCE_PASSWORD: mypassword

