apiVersion: v1
kind: Service
metadata:
  name: exchange-generator-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: exchange-generator-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8084
