apiVersion: v1
kind: Service
metadata:
  name: exchange-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: exchange-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8085
