apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-microservice
  template:
    metadata:
      labels:
        app: accounts-microservice
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.SPRING_DATASOURCE_URL }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.env.SPRING_DATASOURCE_USERNAME }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.env.SPRING_DATASOURCE_PASSWORD }}"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-microservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: accounts-microservice
