apiVersion: v1
kind: Service
metadata:
  name: accounts-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: accounts-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
