global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8085'
          - 'host.docker.internal:8089'
          - 'host.docker.internal:8081'
          - 'host.docker.internal:8086'
          - 'host.docker.internal:8087'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8084'
          - 'host.docker.internal:8083'
rule_files:
  - "alerts.yml"
      
