#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: api-gateway:127.0.0.1:8081
#    ip-address: 127.0.0.1
#    hostname: localhost
#    non-secure-port: 8081
#    status-page-url: http://127.0.0.1:8081/actuator/info
#    health-check-url: http://127.0.0.1:8081/actuator/health
#    home-page-url: http://127.0.0.1:8081/
#spring:
#  application:
#    name: accounts-microservice
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/auth_rk
#    username: postgres
#    password: 1
#  sql:
#    init:
#      mode: always
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#server:
#  port: 8086
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: transfer-microservice:127.0.0.1:8086
#    ip-address: 127.0.0.1
#    hostname: localhost
#    non-secure-port: 8086
#    status-page-url: http://127.0.0.1:8086/actuator/info
#    health-check-url: http://127.0.0.1:8086/actuator/health
#    home-page-url: http://127.0.0.1:8086/
#spring:
#  application:
#    name: transfer-microservice
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

spring:
  application:
    name: accounts-microservice
  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        default-context: application
        format: yaml

