apiVersion: v1
kind: Service
metadata:
  name: cash-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cash-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
